## <div align="center"> TUGAS LAB IS388 Data Analysis </div>
## <div align="center"> WEEK [03]: [Data Manipulation & SQL Basic Query]</div>
#### <div align="center"> Semester Ganjil 2024/2025 </div>
---

In [40]:
import datetime
import uuid

studentName = "Joyandro Gerard Diasz"
studentNIM = "00000158474"
studentClass = "B"

In [41]:
myDate = datetime.datetime.now()
myDevice = str(uuid.uuid1())

print("Name: \t\t{}".format(studentName))
print("NIM: \t\t{}".format(studentNIM))
print("NIM: \t\t{}".format(studentClass))
print("Start: \t\t{}".format(myDate))
print("Device ID: \t{}".format(myDevice))

Name: 		Joyandro Gerard Diasz
NIM: 		00000158474
NIM: 		B
Start: 		2026-09-12 14:45:27.379334
Device ID: 	ebb429ff-ae7d-11f1-9b79-24b2b965c072

---

## <div align="center"> Guided Lab </div>

### Enter Guided Lab Code Here:

In [42]:
import sys 
print(f'Python: {sys.version}')

import numpy as np
print(f'numpy: {np.__version__}')

import pandas as pd
print(f'pandas: {pd.__version__}')

import matplotlib
print(f'matplotlib: {matplotlib.__version__}')

import seaborn as sns
print(f'seaborn: {sns.__version__}')

import sklearn as sk
print(f'sklearn: {sk.__version__}')

import sqlite3
print(f'sqlite3: {sqlite3.sqlite_version}')

Python: 3.14.0 (tags/v3.14.0:ebf955d, Oct  7 2025, 10:15:03) [MSC v.1944 64 bit (AMD64)]
numpy: 2.5.2
pandas: 3.0.5
matplotlib: 3.11.1
seaborn: 0.13.2
sklearn: 1.9.1
sqlite3: 3.50.4

In [43]:
# Ensure the connection to the SQLite database is established
con = sqlite3.connect('FinalDB.sqlite')
cur = con.cursor()

In [44]:
data_sensus = pd.read_csv('./dataset/CensusData.csv')
data_sekolah = pd.read_csv('./dataset/PublicSchools.csv')
data_kriminal = pd.read_csv('./dataset/CrimeData.csv')

In [45]:
# First droping tables if exists cuz we are going to add them in next cell
cur.execute('DROP TABLE IF EXISTS data_sensus')
cur.execute('DROP TABLE IF EXISTS data_sekolah')
cur.execute('DROP TABLE IF EXISTS data_kriminal ')

In [46]:
data_sensus.head()

,COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME,PERCENT_OF_HOUSING_CROWDED,PERCENT_HOUSEHOLDS_BELOW_POVERTY,PERCENT_AGED_16__UNEMPLOYED,PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA,PERCENT_AGED_UNDER_18_OR_OVER_64,PER_CAPITA_INCOME,HARDSHIP_INDEX
0,1.0,Rogers Park,7.7,23.6,8.7,18.2,27.5,23939,39.0
1,2.0,West Ridge,7.8,17.2,8.8,20.8,38.5,23040,46.0
2,3.0,Uptown,3.8,24.0,8.9,11.8,22.2,35787,20.0
3,4.0,Lincoln Square,3.4,10.9,8.2,13.4,25.5,37524,17.0
4,5.0,North Center,0.3,7.5,5.2,4.5,26.2,57123,6.0

In [47]:
data_sekolah.head()

,School_ID,NAME_OF_SCHOOL,"Elementary, Middle, or High School",Street_Address,City,State,ZIP_Code,Phone_Number,Link,Network_Manager,...,Freshman_on_Track_Rate__,X_COORDINATE,Y_COORDINATE,Latitude,Longitude,COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME,Ward,Police_District,Location
0,610038,Abraham Lincoln Elementary School,ES,615 W Kemper Pl,Chicago,IL,60614,(773) 534-5720,http://schoolreports.cps.edu/SchoolProgressRep...,Fullerton Elementary Network,...,NDA,1171699.458,1915829.428,41.924497,-87.644522,7,LINCOLN PARK,43,18,"(41.92449696, -87.64452163)"
1,610281,Adam Clayton Powell Paideia Community Academy ...,ES,7511 S South Shore Dr,Chicago,IL,60649,(773) 535-6650,http://schoolreports.cps.edu/SchoolProgressRep...,Skyway Elementary Network,...,NDA,1196129.985,1856209.466,41.760324,-87.556736,43,SOUTH SHORE,7,4,"(41.76032435, -87.55673627)"
2,610185,Adlai E Stevenson Elementary School,ES,8010 S Kostner Ave,Chicago,IL,60652,(773) 535-2280,http://schoolreports.cps.edu/SchoolProgressRep...,Midway Elementary Network,...,NDA,1148427.165,1851012.215,41.747111,-87.731702,70,ASHBURN,13,8,"(41.74711093, -87.73170248)"
3,609993,Agustin Lara Elementary Academy,ES,4619 S Wolcott Ave,Chicago,IL,60609,(773) 535-4389,http://schoolreports.cps.edu/SchoolProgressRep...,Pershing Elementary Network,...,NDA,1164504.290,1873959.199,41.809757,-87.672145,61,NEW CITY,20,9,"(41.8097569, -87.6721446)"
4,610513,Air Force Academy High School,HS,3630 S Wells St,Chicago,IL,60609,(773) 535-1590,http://schoolreports.cps.edu/SchoolProgressRep...,Southwest Side High School Network,...,91.8,1175177.622,1880745.126,41.828146,-87.632794,34,ARMOUR SQUARE,11,9,"(41.82814609, -87.63279369)"

In [48]:
data_kriminal.head()

,ID,CASE_NUMBER,DATE,BLOCK,IUCR,PRIMARY_TYPE,DESCRIPTION,LOCATION_DESCRIPTION,ARREST,DOMESTIC,...,DISTRICT,WARD,COMMUNITY_AREA_NUMBER,FBICODE,X_COORDINATE,Y_COORDINATE,YEAR,LATITUDE,LONGITUDE,LOCATION
0,3512276,HK587712,2004-08-28,047XX S KEDZIE AVE,890,THEFT,FROM BUILDING,SMALL RETAIL STORE,False,False,...,9,14.0,58.0,6,1155838.0,1873050.0,2004,41.807440,-87.703956,"(41.8074405, -87.703955849)"
1,3406613,HK456306,2004-06-26,009XX N CENTRAL PARK AVE,820,THEFT,$500 AND UNDER,OTHER,False,False,...,11,27.0,23.0,6,1152206.0,1906127.0,2004,41.898280,-87.716406,"(41.898279962, -87.716405505)"
2,8002131,HT233595,2011-04-04,043XX S WABASH AVE,820,THEFT,$500 AND UNDER,NURSING HOME/RETIREMENT HOME,False,False,...,2,3.0,38.0,6,1177436.0,1876313.0,2011,41.815933,-87.624642,"(41.815933131, -87.624642127)"
3,7903289,HT133522,2010-12-30,083XX S KINGSTON AVE,840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,...,4,7.0,46.0,6,1194622.0,1850125.0,2010,41.743665,-87.562463,"(41.743665322, -87.562462756)"
4,10402076,HZ138551,2016-02-02,033XX W 66TH ST,820,THEFT,$500 AND UNDER,ALLEY,False,False,...,8,15.0,66.0,6,1155240.0,1860661.0,2016,41.773455,-87.706480,"(41.773455295, -87.706480471)"

In [49]:
data_kriminal.info()

<class 'pandas.DataFrame'>
RangeIndex: 533 entries, 0 to 532
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     533 non-null    int64
 1   CASE_NUMBER            533 non-null    str
 2   DATE                   533 non-null    str
 3   BLOCK                  533 non-null    str
 4   IUCR                   533 non-null    str
 5   PRIMARY_TYPE           533 non-null    str
 6   DESCRIPTION            533 non-null    str
 7   LOCATION_DESCRIPTION   533 non-null    str
 8   ARREST                 533 non-null    bool
 9   DOMESTIC               533 non-null    bool
 10  BEAT                   533 non-null    int64
 11  DISTRICT               533 non-null    int64
 12  WARD                   490 non-null    float64
 13  COMMUNITY_AREA_NUMBER  490 non-null    float64
 14  FBICODE                533 non-null    str
 15  X_COORDINATE           529 non-null    float64
 16  Y_COORDINATE           529 non-null    float64
 17  YEAR                   533 non-null    int64
 18  LATITUDE               529 non-null    float64
 19  LONGITUDE              529 non-null    float64
 20  LOCATION               529 non-null    str
dtypes: bool(2), float64(6), int64(4), str(9)
memory usage: 80.3 KB

In [50]:
data_kriminal["DATE"] = pd.to_datetime(data_kriminal["DATE"])
data_kriminal.info()

<class 'pandas.DataFrame'>
RangeIndex: 533 entries, 0 to 532
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     533 non-null    int64
 1   CASE_NUMBER            533 non-null    str
 2   DATE                   533 non-null    datetime64[us]
 3   BLOCK                  533 non-null    str
 4   IUCR                   533 non-null    str
 5   PRIMARY_TYPE           533 non-null    str
 6   DESCRIPTION            533 non-null    str
 7   LOCATION_DESCRIPTION   533 non-null    str
 8   ARREST                 533 non-null    bool
 9   DOMESTIC               533 non-null    bool
 10  BEAT                   533 non-null    int64
 11  DISTRICT               533 non-null    int64
 12  WARD                   490 non-null    float64
 13  COMMUNITY_AREA_NUMBER  490 non-null    float64
 14  FBICODE                533 non-null    str
 15  X_COORDINATE           529 non-null    float64
 16  Y_COORDINATE           529 non-null    float64
 17  YEAR                   533 non-null    int64
 18  LATITUDE               529 non-null    float64
 19  LONGITUDE              529 non-null    float64
 20  LOCATION               529 non-null    str
dtypes: bool(2), datetime64[us](1), float64(6), int64(4), str(8)
memory usage: 80.3 KB

In [51]:
data_sensus.info()

<class 'pandas.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 9 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   COMMUNITY_AREA_NUMBER                         77 non-null     float64
 1   COMMUNITY_AREA_NAME                           78 non-null     str
 2   PERCENT_OF_HOUSING_CROWDED                    78 non-null     float64
 3   PERCENT_HOUSEHOLDS_BELOW_POVERTY              78 non-null     float64
 4   PERCENT_AGED_16__UNEMPLOYED                   78 non-null     float64
 5   PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA  78 non-null     float64
 6   PERCENT_AGED_UNDER_18_OR_OVER_64              78 non-null     float64
 7   PER_CAPITA_INCOME                             78 non-null     int64
 8   HARDSHIP_INDEX                                77 non-null     float64
dtypes: float64(7), int64(1), str(1)
memory usage: 5.6 KB

In [52]:
data_sensus.rename(columns = {'PERCENT_HOUSEHOLDS_BELOW_POVERTY':'POVERTY_RATE', 'PERCENT_AGED_16__UNEMPLOYED':'UNEMPLOYMENT_RATE', 'PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA':'NO_DIPLOMA_RATE','PERCENT_AGED_UNDER_18_OR_OVER_64':'DEPENDENT_AGE_RATE'}, inplace = True)
data_sensus.info()

<class 'pandas.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   COMMUNITY_AREA_NUMBER       77 non-null     float64
 1   COMMUNITY_AREA_NAME         78 non-null     str
 2   PERCENT_OF_HOUSING_CROWDED  78 non-null     float64
 3   POVERTY_RATE                78 non-null     float64
 4   UNEMPLOYMENT_RATE           78 non-null     float64
 5   NO_DIPLOMA_RATE             78 non-null     float64
 6   DEPENDENT_AGE_RATE          78 non-null     float64
 7   PER_CAPITA_INCOME           78 non-null     int64
 8   HARDSHIP_INDEX              77 non-null     float64
dtypes: float64(7), int64(1), str(1)
memory usage: 5.6 KB

In [53]:
df1 = data_sensus[['COMMUNITY_AREA_NAME','UNEMPLOYMENT_RATE','NO_DIPLOMA_RATE','PER_CAPITA_INCOME']]
df1.head()

  COMMUNITY_AREA_NAME  UNEMPLOYMENT_RATE  NO_DIPLOMA_RATE  PER_CAPITA_INCOME
0         Rogers Park                8.7             18.2              23939
1          West Ridge                8.8             20.8              23040
2              Uptown                8.9             11.8              35787
3      Lincoln Square                8.2             13.4              37524
4        North Center                5.2              4.5              57123

In [54]:
df1.loc[:, 'COUNT_INCOME'] = np.where(
    df1['PER_CAPITA_INCOME'] > 30000,
    'HIGH',
    np.where(
        df1['PER_CAPITA_INCOME'] < 30000,
        'LOW',
        'MEDIUM'
    )
)

In [55]:
df1.head(10)

,COMMUNITY_AREA_NAME,UNEMPLOYMENT_RATE,NO_DIPLOMA_RATE,PER_CAPITA_INCOME,COUNT_INCOME
0,Rogers Park,8.7,18.2,23939,LOW
1,West Ridge,8.8,20.8,23040,LOW
2,Uptown,8.9,11.8,35787,HIGH
3,Lincoln Square,8.2,13.4,37524,HIGH
4,North Center,5.2,4.5,57123,HIGH
5,Lake View,4.7,2.6,60058,HIGH
6,Lincoln Park,5.1,3.6,71551,HIGH
7,Near North Side,7.0,2.5,88669,HIGH
8,Edison Park,6.5,7.4,40959,HIGH
9,Norwood Park,9.0,11.5,32875,HIGH

In [56]:
df1_dropped = df1.drop("COUNT_INCOME", axis=1)
df1_dropped.head()

  COMMUNITY_AREA_NAME  UNEMPLOYMENT_RATE  NO_DIPLOMA_RATE  PER_CAPITA_INCOME
0         Rogers Park                8.7             18.2              23939
1          West Ridge                8.8             20.8              23040
2              Uptown                8.9             11.8              35787
3      Lincoln Square                8.2             13.4              37524
4        North Center                5.2              4.5              57123

In [57]:
data_sekolah[data_sekolah['COMMUNITY_AREA_NAME'] == 'SOUTH SHORE']

,School_ID,NAME_OF_SCHOOL,"Elementary, Middle, or High School",Street_Address,City,State,ZIP_Code,Phone_Number,Link,Network_Manager,...,Freshman_on_Track_Rate__,X_COORDINATE,Y_COORDINATE,Latitude,Longitude,COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME,Ward,Police_District,Location
1,610281,Adam Clayton Powell Paideia Community Academy ...,ES,7511 S South Shore Dr,Chicago,IL,60649,(773) 535-6650,http://schoolreports.cps.edu/SchoolProgressRep...,Skyway Elementary Network,...,NDA,1196129.985,1856209.466,41.760324,-87.556736,43,SOUTH SHORE,7,4,"(41.76032435, -87.55673627)"
122,609815,Edward A Bouchet Math & Science Academy Elemen...,ES,7355 S Jeffery Blvd,Chicago,IL,60649,(773) 535-0501,http://schoolreports.cps.edu/SchoolProgressRep...,Skyway Elementary Network,...,NDA,1190861.978,1856358.038,41.760861,-87.576038,43,SOUTH SHORE,5,3,"(41.76086093, -87.57603849)"
145,609916,Enrico Fermi Elementary School,ES,1415 E 70th St,Chicago,IL,60637,(773) 535-0540,http://schoolreports.cps.edu/SchoolProgressRep...,Skyway Elementary Network,...,NDA,1186924.786,1858826.102,41.767728,-87.590390,43,SOUTH SHORE,5,3,"(41.76772772, -87.59039017)"
222,610297,High School of Leadership at South Shore,HS,7627 S Constance Ave,Chicago,IL,60649,(773) 535-6190,http://schoolreports.cps.edu/SchoolProgressRep...,South Side High School Network,...,48.8,1189903.206,1854648.757,41.756194,-87.579607,43,SOUTH SHORE,8,4,"(41.75619362, -87.57960727)"
238,610103,Isabelle C O'Keeffe Elementary School,ES,6940 S Merrill Ave,Chicago,IL,60649,(773) 535-0600,http://schoolreports.cps.edu/SchoolProgressRep...,Skyway Elementary Network,...,NDA,1191708.826,1859191.464,41.768616,-87.572843,43,SOUTH SHORE,5,3,"(41.76861557, -87.57284299)"
247,610047,James Madison Elementary School,ES,7433 S Dorchester Ave,Chicago,IL,60619,(773) 535-0551,http://schoolreports.cps.edu/SchoolProgressRep...,Skyway Elementary Network,...,NDA,1186872.582,1855846.347,41.759552,-87.590676,43,SOUTH SHORE,5,3,"(41.75955224, -87.59067582)"
390,609806,Myra Bradwell Communications Arts & Sciences E...,ES,7736 S Burnham Ave,Chicago,IL,60649,(773) 535-6600,http://schoolreports.cps.edu/SchoolProgressRep...,AUSL Schools,...,NDA,1196028.811,1854039.898,41.754373,-87.557179,43,SOUTH SHORE,7,4,"(41.7543734, -87.55717881)"
425,610116,Parkside Elementary Community Academy,ES,6938 S East End Ave,Chicago,IL,60649,(773) 535-0940,http://schoolreports.cps.edu/SchoolProgressRep...,Skyway Elementary Network,...,NDA,1188940.542,1859149.081,41.768566,-87.582991,43,SOUTH SHORE,5,3,"(41.76856599, -87.58299131)"
484,610530,South Shore Fine Arts Academy,ES,1415 E 70th St,Chicago,IL,60637,(773) 535-8340,http://schoolreports.cps.edu/SchoolProgressRep...,Skyway Elementary Network,...,NDA,1186924.786,1858826.102,41.767728,-87.590390,43,SOUTH SHORE,5,3,"(41.76772772, -87.59039017)"

In [58]:
data_sekolah[data_sekolah['NAME_OF_SCHOOL'].str.contains('South')]

,School_ID,NAME_OF_SCHOOL,"Elementary, Middle, or High School",Street_Address,City,State,ZIP_Code,Phone_Number,Link,Network_Manager,...,Freshman_on_Track_Rate__,X_COORDINATE,Y_COORDINATE,Latitude,Longitude,COMMUNITY_AREA_NUMBER,COMMUNITY_AREA_NAME,Ward,Police_District,Location
64,610345,Carter G Woodson South Elementary School,ES,4414 S Evans,Chicago,IL,60653,(773) 535-1280,http://schoolreports.cps.edu/SchoolProgressRep...,Burnham Park Elementary Network,...,NDA,1181853.018,1875820.129,41.814480,-87.608455,38,GRAND BOULEVARD,3,2,"(41.81447955, -87.60845505)"
222,610297,High School of Leadership at South Shore,HS,7627 S Constance Ave,Chicago,IL,60649,(773) 535-6190,http://schoolreports.cps.edu/SchoolProgressRep...,South Side High School Network,...,48.8,1189903.206,1854648.757,41.756194,-87.579607,43,SOUTH SHORE,8,4,"(41.75619362, -87.57960727)"
483,609990,South Loop Elementary School,ES,1212 S Plymouth Ct,Chicago,IL,60605,(773) 534-8690,http://schoolreports.cps.edu/SchoolProgressRep...,Burnham Park Elementary Network,...,NDA,1176190.878,1894860.267,41.866856,-87.628651,33,NEAR SOUTH SIDE,2,1,"(41.86685634, -87.62865124)"
484,610530,South Shore Fine Arts Academy,ES,1415 E 70th St,Chicago,IL,60637,(773) 535-8340,http://schoolreports.cps.edu/SchoolProgressRep...,Skyway Elementary Network,...,NDA,1186924.786,1858826.102,41.767728,-87.590390,43,SOUTH SHORE,5,3,"(41.76772772, -87.59039017)"
485,609745,Southside Occupational Academy High School,HS,7342 S Hoyne Ave,Chicago,IL,60636,(773) 535-9100,http://schoolreports.cps.edu/SchoolProgressRep...,Southwest Side High School Network,...,NDA,1163596.617,1855772.059,41.759868,-87.675984,67,WEST ENGLEWOOD,17,7,"(41.75986813, -87.6759838)"

In [59]:
# Group by 'PRIMARY_TYPE' and calculate the total number of crimes and arrests
crime_grouped = data_kriminal.groupby('PRIMARY_TYPE').agg({
    'ID': 'count',            # Count the total number of crimes for each type
    'ARREST': 'sum'           # Sum the total number of arrests for each type
}).reset_index()

# Rename columns for clarity
crime_grouped.columns = ['Crime Type', 'Total Crimes', 'Total Arrests']

# Display the grouped data
crime_grouped.head()

                          Crime Type  Total Crimes  Total Arrests
0                              ARSON             2              0
1                            ASSAULT            32              9
2                            BATTERY            92             20
3                           BURGLARY            30              1
4  CONCEALED CARRY LICENSE VIOLATION             1              1

In [60]:
# Define specific location and year to filter (e.g., District 9 and Year 2016)
selected_district = 9
selected_year = 2016

# Filter the DataFrame based on the specified district and year
filtered_crimes = data_kriminal[(data_kriminal['DISTRICT'] == selected_district) & (data_kriminal['YEAR'] == selected_year)]

# Use groupby with agg on the filtered data
grouped_filtered_crimes = filtered_crimes.groupby('PRIMARY_TYPE').agg(
    Total_Crimes=('ID', 'count'),                # Count total number of crimes for each type
    Total_Arrests=('ARREST', 'sum'),             # Sum the total number of arrests for each type
    Average_Latitude=('LATITUDE', 'mean'),       # Calculate the average latitude for each crime type
    Average_Longitude=('LONGITUDE', 'mean')      # Calculate the average longitude for each crime type
).reset_index()

# Display the grouped data with aggregations
print(grouped_filtered_crimes)

      PRIMARY_TYPE  Total_Crimes  Total_Arrests  Average_Latitude  \
0  CRIMINAL DAMAGE             1              0         41.824353
1    OTHER OFFENSE             2              0         41.809813

   Average_Longitude
0         -87.707841
1         -87.676798

In [61]:
#merge based on assumed column names
kriminal = crime_grouped.merge(data_kriminal, 
                               left_on='Crime Type',  # Adjusted to correct column name in crime_grouped
                               right_on='PRIMARY_TYPE',  # Adjusted to correct column name in data_kriminal
                               suffixes=(False, False))

In [62]:
kriminal

,Crime Type,Total Crimes,Total Arrests,ID,CASE_NUMBER,DATE,BLOCK,IUCR,PRIMARY_TYPE,DESCRIPTION,...,DISTRICT,WARD,COMMUNITY_AREA_NUMBER,FBICODE,X_COORDINATE,Y_COORDINATE,YEAR,LATITUDE,LONGITUDE,LOCATION
0,ARSON,2,0,9692995,HX343113,2014-07-13,132XX S RIVERDALE AVE,1025,ARSON,AGGRAVATED,...,5,9.0,54.0,9,1182053.0,1817235.0,2014,41.653711,-87.609529,"(41.653710537, -87.609528714)"
1,ARSON,2,0,4607081,HM195342,2006-02-22,001XX W 118TH ST,1020,ARSON,BY FIRE,...,5,34.0,53.0,9,1177509.0,1826708.0,2006,41.679809,-87.625870,"(41.679809448, -87.625870438)"
2,ASSAULT,32,9,5322667,HN182437,2007-02-17,091XX S COTTAGE GROVE AVE,560,ASSAULT,SIMPLE,...,6,8.0,44.0,08A,1183165.0,1844391.0,2007,41.728205,-87.604619,"(41.728204555, -87.604619408)"
3,ASSAULT,32,9,9348957,HW493063,2013-10-14,011XX N LOREL AVE,530,ASSAULT,AGGRAVATED: OTHER DANG WEAPON,...,15,37.0,25.0,04A,1140468.0,1907012.0,2013,41.900932,-87.759497,"(41.900932034, -87.759497048)"
4,ASSAULT,32,9,2948095,HJ637197,2003-08-30,011XX N KEYSTONE AVE,560,ASSAULT,SIMPLE,...,11,27.0,23.0,08A,1149178.0,1907288.0,2003,41.901525,-87.727497,"(41.901525076, -87.727497088)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,WEAPONS VIOLATION,6,5,7357439,HS100098,2010-01-01,070XX S ROCKWELL ST,143B,WEAPONS VIOLATION,UNLAWFUL POSS OTHER FIREARM,...,8,18.0,66.0,15,1160255.0,1857948.0,2010,41.765909,-87.688171,"(41.765908652, -87.688171087)"
529,WEAPONS VIOLATION,6,5,9432406,HW576249,2013-12-18,012XX S KEDVALE AVE,143A,WEAPONS VIOLATION,UNLAWFUL POSS OF HANDGUN,...,10,24.0,29.0,15,1148913.0,1894068.0,2013,41.865253,-87.728813,"(41.865253059, -87.728812529)"
530,WEAPONS VIOLATION,6,5,3426362,HK485601,2004-07-10,067XX S THROOP ST,143A,WEAPONS VIOLATION,UNLAWFUL POSS OF HANDGUN,...,7,17.0,67.0,15,1168821.0,1860034.0,2004,41.771452,-87.656714,"(41.7714523, -87.656713552)"
531,WEAPONS VIOLATION,6,5,2269553,HH460583,2002-06-22,021XX N ST LOUIS AVE,143A,WEAPONS VIOLATION,UNLAWFUL POSS OF HANDGUN,...,14,26.0,22.0,15,1152922.0,1913821.0,2002,41.919379,-87.713571,"(41.919378841, -87.713571489)"
532,WEAPONS VIOLATION,6,5,4965099,HM576559,2006-09-02,087XX S ESCANABA AVE,143A,WEAPONS VIOLATION,UNLAWFUL POSS OF HANDGUN,...,4,10.0,46.0,15,1196907.0,1847528.0,2006,41.736482,-87.554177,"(41.736482473, -87.554176677)"

In [63]:
# with .to_sql() func we can add our dataframes to our Database

data_sensus.to_sql('data_sensus',con)
data_sekolah.to_sql('data_sekolah',con)
data_kriminal.to_sql('data_kriminal',con)

533

In [64]:
# Find the total number of crimes recorded in the CRIME table.
cur.execute('SELECT COUNT(ID) FROM data_kriminal')
cur.fetchone()

(533,)

In [65]:
# List community areas with per capita income less than 11000.

cur.execute('''SELECT COMMUNITY_AREA_NAME FROM data_sensus
                WHERE PER_CAPITA_INCOME < 11000''')
#Convert result of Query to Pandas Dataframe and rename its Column
pd.DataFrame(cur.fetchall()).rename(columns={0:'COMMUNITY_AREA_NAME'})

  COMMUNITY_AREA_NAME
0  West Garfield Park
1      South Lawndale
2         Fuller Park
3           Riverdale

In [66]:
cur.execute(''' SELECT COMMUNITY_AREA_NAME, C FROM
                (SELECT C ,NUM FROM (SELECT COUNT(*) AS C,
                COMMUNITY_AREA_NUMBER AS NUM FROM data_kriminal
                GROUP BY COMMUNITY_AREA_NUMBER) ORDER BY C DESC LIMIT 2) A
                LEFT JOIN data_sensus B WHERE A.NUM = B.COMMUNITY_AREA_NUMBER ''')

pd.DataFrame(cur.fetchall()).rename(columns={0:'COMMUNITY_AREA_NAME',1:'Count Of Crimes'})

  COMMUNITY_AREA_NAME  Count Of Crimes
0              Austin               43

----

## <div align="center"> Conclusion </div>

### Enter Your Conclusion Here:

----

In [67]:
studentName2 = "Nama2"
studentNIM2 = "NIM2"
studentClass2 = "Class2"

In [68]:
print("Name: \t\t{}".format(studentName2))
print("NIM: \t\t{}".format(studentNIM2))
print("NIM: \t\t{}".format(studentClass2))
print("End: \t\t{}".format(myDate))
print("Device ID: \t{}".format(myDevice))

Name: 		Nama2
NIM: 		NIM2
NIM: 		Class2
End: 		2026-09-12 14:45:27.379334
Device ID: 	ebb429ff-ae7d-11f1-9b79-24b2b965c072

----

## <div align="center"> Reference </div>

### Input Your Reference Here  (Jika ada):

----